iagovrocha/zapcomm

.gitignore
frontend/src/pages/Dashboard/index.js

Modificações feitas por Ana Carolina: mudança dos icons e no tamanho das fontes e cores na grid.

Mudanças no Dashboard Icons e Grid

---

frontend/src/components/NewTicketModal/index.js
frontend/src/components/TicketsManagerTabs/index.js
frontend/src/layout/index.js
frontend/src/pages/TicketsCustom/index.js
frontend/src/translate/languages/pt.js

-  Redesign completo da página de Chamados

Página de Chamados

---

frontend/src/pages/ToDoList/index.js

Alteração de lista para tabela, adição do cabeçalho conforme o protótipo do Figma, ajustes na caixa de texto, no botão de adicionar/salvar, na tabela onde as tarefas são exibidas e nos botões de Editar/Deletar. Organização da área onde os dados serão adicionados, inclusão de cabeçalho para as tarefas, novas funcionalidades, como a exibição de erro ao digitar mais de 50 caracteres e exibição do cabeçalho das tarefas apenas quando houver tarefas. Adição de uma barra separadora entre a caixa de texto e o botão de adicionar/salvar.

Página de tarefas

---

frontend/src/pages/Contacts/index.js
frontend/src/pages/QuickMessages/index.js
frontend/src/pages/ToDoList/index.js

- Alteração na estrutura das barras de pesquisa para o padrão
- Alteração da estrutura da barra de pesquisa do ToDoList e backgroundColor para branco no TodoDoList e QuickMenssages

Desing Fix

---

frontend/src/pages/Contacts/index.js
frontend/src/pages/Dashboard/index.js
frontend/src/pages/QuickMessages/index.js
frontend/src/pages/ToDoList/index.js

- Adição das mudaças debatidas durante a reunião do dia 17.10
- Padronização das páginas

Pull Request de Padronização

---

frontend/src/components/AnnouncementModal/index.js
frontend/src/components/CampaignModal/index.js
frontend/src/components/ContactModal/index.js
frontend/src/components/PromptModal/index.js
frontend/src/components/ScheduleModal/index.js
frontend/src/pages/Annoucements/index.js
frontend/src/pages/Campaigns/index.js
frontend/src/pages/CampaignsConfig/index.js
frontend/src/pages/Contacts/index.js
frontend/src/pages/Dashboard/index.js
frontend/src/pages/Prompts/index.js
frontend/src/pages/QuickMessages/index.js
frontend/src/pages/Schedules/index.js
frontend/src/pages/ToDoList/index.js
frontend/src/translate/languages/pt.js

- Tela de Listagem de Campanhas
- Tela de Configurações de Campanhas
- Tela de Informativos 
- Tela de OpenAi
- Início das modificações na tela de Agendamentos

Telas da Sprint 24/10 - Ana Carolina

---

frontend/src/components/ConfirmationModal/index.js
frontend/src/components/TagModal/index.js
frontend/src/layout/index.js
frontend/src/pages/Tags/index.js
frontend/src/translate/languages/pt.js

- Tela de Tags
- Mudança do BackgroundColor para branco em todas as telas

Tela (Tags) da Sprint 24/10 - Iago Vieira Rocha e Allan Henrique

---

frontend/src/components/TagModal/index.js
frontend/src/pages/Contacts/index.js
frontend/src/pages/QueueIntegration/index.js
frontend/src/pages/QuickMessages/index.js
frontend/src/pages/Tags/index.js

- Redesign da pagina de Integrações
- Modificações na pagina Contatos
- Modificações na pagina Respostas Rápidas

Telas da Sprint 24/10 - Iago Vieira Rocha

---

frontend/src/pages/ContactListItems/index.js
frontend/src/pages/ContactLists/index.js
frontend/src/pages/QuickMessages/index.js

Tela de Lista de Contatos da aba CAMPANHAS pronta, juntamente com a tela de contatos que achamos dentro da página de lista de contatos. (Ajuda de Ana Carolina)

Telas da Sprint 24/10 - Ana Sofia

---

.gitignore
frontend/src/pages/Chat/index.js
frontend/src/pages/Contacts/index.js
frontend/src/pages/QuickMessages/index.js

Telas da Sprint 24/10 - Antônio Calu e Annamel

---

.gitignore
frontend/src/components/TagModal/index.js
frontend/src/pages/Chat/ChatList.js
frontend/src/pages/Chat/ChatMessages.js
frontend/src/pages/Chat/index.js
frontend/src/pages/ContactListItems/index.js
frontend/src/pages/ContactLists/index.js
frontend/src/pages/Contacts/index.js
frontend/src/pages/Helps/index.js
frontend/src/pages/QueueIntegration/index.js
frontend/src/pages/QuickMessages/index.js
frontend/src/pages/Tags/index.js
frontend/src/pages/ToDoList/index.js

Tela de tarefas: Adição da mensagem informando se não houver nenhuma tarefa, juntamente com o cabeçalho das tarefas.
Tela de ajuda: Adição de tabelas a estrutura do site, redesign do cabeçalho para seguir o padrão do figma e das outras telas, adição da caixa de texto e estilização dela, adição da funcionalidade de pesquisa de tutoriais e 
organização das tabelas e correção para que tutoriais possam ser criados apartir da tela de configurações.

Tela de ajuda e tela de tarefas

---

frontend/src/components/FileModal/index.js
frontend/src/pages/Files/index.js
frontend/src/pages/QueueIntegration/index.js
frontend/src/pages/Schedules/Schedules.css
frontend/src/pages/Tags/index.js

- Organização nos padrões das páginas
- Tela de Lista de Arquivos
- Tela de Agendamentos

Telas da Sprint 31/10 - Ana Carolina

---

frontend/src/pages/Helps/index.js
frontend/src/pages/MessagesAPI/index.js

Tela de ajuda: ajuste dos espaçamentos.
Tela de API: redesign do cabeçalho, adição de uma barra abaixo dele, ajuste dos espaçamentos dos conteúdos e redesign dos botões.

Tela de ajuda e de API

---

frontend/src/components/ConfirmationModal/index.js
frontend/src/components/UserModal/index.js
frontend/src/pages/Users/index.js
frontend/src/translate/languages/pt.js

Telas da Sprint 31/10 - Iago Vieira Rocha e Allan Henrique

---

frontend/src/components/QueueModal/index.js
frontend/src/components/QuickMessageDialog/index.js
frontend/src/pages/Chat/ChatList.js
frontend/src/pages/Chat/ChatMessages.js
frontend/src/pages/Chat/index.js
frontend/src/pages/Queues/index.js

- Filas & ChatBot
- Ajuste do Chat Interno
- Ajuste em Resposta Rápidas _(Interface de Adicionar Respostas)_

Telas da Sprint 31/10 - Annamel Moura e Antônio Calu

---

frontend/src/components/Settings/Options.js
frontend/src/pages/SettingsCustom/index.js

Mudanças na página de configurações, com a ajuda de Ana Carolina.

Telas da Sprint 31/10 - Ana Sofia

---

frontend/src/pages/Connections/index.js

padronizei o layout e fiz o search input funcionar apropriadamente

Telas da sprint 31/10 Eric Fontes

---

frontend/src/components/QueueModal/index.js
frontend/src/pages/Queues/index.js

As mudanças que foram feitas nessa tela tiveram ajuda de Ana Carolina, Annamel Moura, Ântonio Calu.

Tela de Filas & Chatbot - 6/11

---

frontend/src/components/AnnouncementModal/index.js
frontend/src/components/CampaignModal/index.js
frontend/src/components/ContactModal/index.js
frontend/src/components/FileModal/index.js
frontend/src/components/PromptModal/index.js
frontend/src/components/ScheduleModal/index.js
frontend/src/pages/Prompts/index.js
frontend/src/translate/languages/pt.js

- Formatação do modal da tela de Contatos
- Formatação do modal da tela de Agendamentos
- Formatação do modal da tela de Listagem de Campanhas
- Formatação do modal da tela de Informativos
- Formatação do modal da tela de Lista de Arquivos
- Adição da barra de pesquisa de Prompts

Adição da barra de pesquisa na tela de Prompts e formatação dos Modals

---

frontend/src/components/NewTicketModal/index.js
frontend/src/components/QueueIntegrationModal/index.js
frontend/src/components/TagModal/index.js
frontend/src/components/UserModal/index.js
frontend/src/pages/TicketsCustom/index.js
frontend/src/pages/Users/index.js

- Modificado Users
- Modificado Chamados
- Modificado Integrações 
- Modificado Tag

Padronização das paginas Users, Chamados, Integrações e Tag

---

frontend/src/components/TaskModal/index.js
frontend/src/components/WhatsAppModal/index.js
frontend/src/pages/Connections/index.js
frontend/src/pages/Helps/index.js
frontend/src/pages/ToDoList/index.js

Tela de ajuda: Adição de icones de video ao lado do nome dos tutoriais.
Tela de Tarefas: Ajuste nos botões de editar e deletar para ficar padronizado com as outras telas, criação de um modal para adcionar e editar as tarefas e adaptação para funcionamento do input de pesquisa.
Tela de Conexões: Ajuste nos espaçamentos para ficar padrão com as outras páginas e reedesign do modal da página de conexões.
As mudanças que foram feitas na tela de conexões, teve ajuda de Eric Fontes

Tela de Ajuda, Tarefas e Conexões

---

frontend/src/components/ContactListDialog/index.js
frontend/src/components/ContactListItemModal/index.js

Mudanças nos modals da página de Lista de Contatos

---

frontend/src/components/WhatsAppModal/index.js
frontend/src/pages/Connections/index.js
frontend/src/pages/Helps/index.js

Tela de ajuda: Espaçamento entre titulo de tutorial e icone de video
Modal Tela de Conexões: Ajuste nas caixas de seleções, e redesign do botão de adicionar/editar

Tela de ajuda e Modal de conexôes

---

frontend/src/layout/index.js
frontend/src/pages/Dashboard/ChartsDate.js
frontend/src/pages/Dashboard/ChartsUser.js
frontend/src/pages/Dashboard/index.js
frontend/src/pages/Schedules/index.js

- Alteração na barra da tela de Agendamentos
- Correção da logo do site na header
- Layout dashboard

Modificações no padrão e no Dashboard

---

frontend/src/components/ContactTag/index.js
frontend/src/components/TagsContainer/index.js
frontend/src/layout/index.js
frontend/src/pages/Tags/index.js

- Mudança no layout/index.js
- Estilização de Tags em Chamados

Mudança do mainList para responsividade para dispositivos moveis e estilização

---

frontend/src/components/WhatsAppModal/index.js
frontend/src/pages/Connections/index.js

Adiçao de comentarios explicativos nas telas citadas acima

Tela de conexoes e whatsappModal comentadas

---

frontend/src/pages/Chat/ChatList.js
frontend/src/pages/Chat/ChatMessages.js
frontend/src/pages/Chat/index.js

Modificações na lista de contatos, na parte de mensagens  e no botão 'Salvar'.

Chat Interno

---

frontend/src/pages/Connections/index.js

tela de conexoes e whatssap modal comentadas

Tela de conexoes consertada
